from fastapi import APIRouter, HTTPException, Depends, Request, logger
from typing import List
from api.schemas import (
    RiskPredictionRequest, RiskPredictionResponse, FrontendTriageResponse, 
    PatientSyncResponse, TwinStateResponse, FrontendPredictRequest,
    FrontendSimulateRequest, FrontendSimulateResponse, TelemetryData,
    BatchPredictionRequest, BatchPredictionResponse, TreatmentSimulationRequest,
    TreatmentSimulationResponse
)
from models.inference import predict_triage_severity
from models.manager import ModelManager, model_manager
from utils.llm import generate_clinical_explanation
from preprocessing.inference_preprocessor import InferencePreprocessor
from core.security import get_api_key, limiter

router = APIRouter(dependencies=[Depends(get_api_key)])
preprocessor = InferencePreprocessor()

@router.get("/health", tags=["System"])
@limiter.limit("60/minute")
async def health_check(request: Request):
    """Health check endpoint containing ML model status."""
    from models.manager import model_manager
    import datetime
    
    metadata = model_manager.metadata
    
    timestamp = metadata.get("timestamp")
    formatted_time = "unknown"
    if isinstance(timestamp, (int, float)):
        formatted_time = datetime.datetime.fromtimestamp(timestamp).isoformat()
        
    return {
        "status": "ok", 
        "message": "Healthcare Digital Twin API is running.",
        "ml_status": "healthy" if metadata.get("status") == "loaded" else "degraded",
        "model_version": metadata.get("version"),
        "model_status": metadata.get("status"),
        "training_timestamp": formatted_time,
        "error": metadata.get("error")
    }

@router.post("/patients/sync", response_model=PatientSyncResponse, tags=["Patient Data"])
@limiter.limit("10/minute")
async def sync_patient_data(data: TelemetryData, request: Request):
    """
    Simulates syncing patient data from EHR (Epic/Cerner) via FHIR.
    """
    return PatientSyncResponse(
        status="success",
        message="Telemetry data synced successfully",
        patient_id=data.patient_id
    )

@router.get("/twin/{patient_id}", response_model=TwinStateResponse, tags=["Digital Twin"])
@limiter.limit("30/minute")
async def get_digital_twin(patient_id: str, request: Request):
    """
    Retrieves the current state of a patient's digital twin.
    """
    return TwinStateResponse(
        patient_id=patient_id,
        current_vitals={
            "heart_rate": 82,
            "blood_pressure": "120/80",
            "spO2": 98.5
        },
        baseline_deviation=2.4,
        last_updated="2023-10-27T10:00:00Z"
    )

@router.post("/predict/risk", response_model=RiskPredictionResponse, tags=["Prediction"])
@limiter.limit("100/minute")
async def predict_risk(request_data: RiskPredictionRequest, request: Request):
    """
    Returns diagnostic predictions exclusively generated by the ML model.
    Includes advanced inference preprocessing, validation, and LRU caching.
    """
    if request_data.telemetry:
        raw_data = request_data.telemetry.dict()
    else:
        raise HTTPException(status_code=400, detail="Telemetry data is required.")
    
    try:
        clean_data, _ = preprocessor.validate_and_preprocess(raw_data)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    
    ml_result = await model_manager.predict_async(clean_data)
    
    explanation = None
    if request_data.include_explanation and "explanations" in ml_result:
        explanation = ml_result["explanations"]
        
    return RiskPredictionResponse(
        patient_id=request_data.patient_id,
        severity_score=ml_result.get("severity_score", 0.0),
        priority=ml_result.get("priority_category", "Unknown"),
        estimated_wait_time=ml_result.get("waiting_priority", "Unknown"),
        confidence=ml_result.get("confidence", 0.95),
        top_shap_contributors=explanation
    )

@router.post("/predict/risk/batch", response_model=BatchPredictionResponse, tags=["Prediction"])
@limiter.limit("20/minute")
async def predict_risk_batch(request_data: BatchPredictionRequest, request: Request):
    """
    High-throughput endpoint for batch predictions.
    """
    clean_payloads = []
    patient_ids = []
    
    for p in request_data.patients:
        patient_ids.append(p.patient_id)
        raw_data = p.telemetry.dict() if p.telemetry else {"patient_id": p.patient_id}
        try:
            clean, _ = preprocessor.validate_and_preprocess(raw_data)
            clean_payloads.append(clean)
        except ValueError as e:
            # Drop invalid payloads or handle differently
            continue
            
    batch_results = await model_manager.predict_batch_async(clean_payloads)
    
    final_results = []
    for pid, ml_result in zip(patient_ids, batch_results):
        final_results.append(RiskPredictionResponse(
            patient_id=pid,
            severity_score=ml_result.get("severity_score", 0.0),
            priority=ml_result.get("priority_category", "Unknown"),
            estimated_wait_time=ml_result.get("waiting_priority", "Unknown"),
            confidence=ml_result.get("confidence", 0.95),
            top_shap_contributors=ml_result.get("explanations")
        ))
        
    return BatchPredictionResponse(results=final_results)



@router.post("/predict/frontend", response_model=FrontendTriageResponse, tags=["Predictions"])
@limiter.limit("100/minute")
async def predict_frontend(request_data: FrontendPredictRequest, request: Request):
    """
    Frontend-specific endpoint for Triage Severity Prediction.
    Calculates severity score, priority category, and waiting priority using the trained regressor model.
    """
    model_manager = ModelManager()
    
    if not model_manager.model:
        logger.error("Predict endpoint called but ML model is not loaded.")
        raise HTTPException(
            status_code=503,
            detail="Triage ML model is currently unavailable or failed to load. Please check server logs."
        )

    try:
        import logging
        log = logging.getLogger(__name__)
        # We pass the raw frontend JSON dictionary to the inference engine.
        result = predict_triage_severity(
            patient_data=request_data.model_dump(),
            model=model_manager.model,
            preprocessor=model_manager.preprocessor,
            feature_list=model_manager.feature_list,
            include_explanation=True
        )
        return result
    except Exception as e:
        log.error(f"Error during triage prediction: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal server error during triage assessment.")

@router.post("/simulate/frontend", response_model=FrontendSimulateResponse, tags=["Digital Twin"])
@limiter.limit("100/minute")
async def simulate_frontend(request_data: FrontendSimulateRequest, request: Request):
    """
    Frontend-specific endpoint for Digital Twin simulation.
    Uses CatBoost to infer real-time Severity Score based on updated vitals.
    """
    model_manager = ModelManager()
    
    if not model_manager.model:
        raise HTTPException(
            status_code=503,
            detail="Triage ML model is currently unavailable."
        )

    # 1. Ask CatBoost for real prediction
    inference_result = predict_triage_severity(
        patient_data=request_data.model_dump(),
        model=model_manager.model,
        preprocessor=model_manager.preprocessor,
        feature_list=model_manager.feature_list,
        include_explanation=False
    )
    
    risk = inference_result["priority_category"]
    severity_score = inference_result["severity_score"]
    wait_time = inference_result["waiting_priority"]
    
    # 2. Maintain UI specific visual mocks (Organ Systems, Trends, UI colors) 
    # but base them on the real `risk` calculated above
    syms = request_data.symptoms
    hasCardiac = "chest pain" in syms or "shortness of breath" in syms
    hasFever = "fever" in syms or request_data.temp > 37.5
    hasNeuro = "dizziness" in syms or "headache" in syms or "tremors" in syms
    
    hrN = request_data.hr
    sbpN = request_data.sbp
    spo2N = request_data.spo2
    
    primaryCondition = "Acute Cardiovascular Stress" if hasCardiac else "Systemic Inflammatory Response" if hasFever else "Neurological Dysfunction" if hasNeuro else "Multi-Symptom Syndrome"
    
    organSystems = [
      { "name": "Cardiovascular", "health": 54 if hasCardiac else 68 if hrN > 100 else 85, "status": "Stressed" if hasCardiac else "Borderline" if hrN > 100 else "Normal", "icon": "❤️" },
      { "name": "Respiratory", "health": 58 if spo2N < 94 else 72 if "cough" in syms else 91, "status": "Critical" if spo2N < 94 else "Borderline" if "cough" in syms else "Normal", "icon": "🫁" },
      { "name": "Neurological", "health": 63 if hasNeuro else 89, "status": "Borderline" if hasNeuro else "Normal", "icon": "🧠" },
      { "name": "Hepatic", "health": 71 if "nausea" in syms or "vomiting" in syms else 88, "status": "Borderline" if "nausea" in syms else "Normal", "icon": "🫀" },
      { "name": "Renal", "health": 70 if request_data.glucose > 140 else 87, "status": "Borderline" if request_data.glucose > 140 else "Normal", "icon": "🫘" },
      { "name": "Immune", "health": 60 if hasFever else 65 if request_data.crp > 10 else 78, "status": "Stressed" if hasFever else "Borderline" if request_data.crp > 10 else "Normal", "icon": "🛡️" }
    ]
    
    vitalStatus = [
      { "label": "Heart Rate", "value": f"{request_data.hr} bpm", "flag": "High" if hrN > 100 else "Low" if hrN < 60 else "Normal" },
      { "label": "Blood Pressure", "value": f"{request_data.sbp}/{request_data.dbp} mmHg", "flag": "High" if sbpN > 140 else "Low" if sbpN < 90 else "Normal" },
      { "label": "Temperature", "value": f"{request_data.temp}°C", "flag": "High" if request_data.temp > 38 else "Low" if request_data.temp < 36 else "Normal" },
      { "label": "SpO2", "value": f"{request_data.spo2}%", "flag": "Critical" if spo2N < 94 else "Low" if spo2N < 97 else "Normal" },
      { "label": "Blood Glucose", "value": f"{request_data.glucose} mg/dL", "flag": "High" if request_data.glucose > 140 else "Low" if request_data.glucose < 70 else "Normal" },
      { "label": "CRP", "value": f"{request_data.crp} mg/L", "flag": "High" if request_data.crp > 10 else "Borderline" if request_data.crp > 5 else "Normal" }
    ]
    
    timeline = [
      { "day": "Day 0", "event": "Digital twin initialized. Baseline vitals captured.", "severity": "info" },
      { "day": "Treatment Plan", "event": f"CatBoost V2 updated Severity Score to {severity_score}/100.", "severity": "warning" if risk in ["High", "Critical"] else "success" }
    ]
    
    rec_base = "a cautious recovery trajectory with a 60-day stabilization window, provided clinical interventions are initiated promptly" if risk == "High" or risk == "Critical" else "a favourable 90-day outlook with adherence to recommended lifestyle and pharmacological adjustments"
    narrative = f"The digital twin for {request_data.name} ({request_data.age}y {request_data.gender}) was constructed using {len(syms)} symptom vectors and baseline vitals. The CatBoost AI engine categorized this patient as {risk} Priority (Score: {severity_score}/100). Under the {request_data.scenario} scenario, the model projects {rec_base}. Organ system cross-talk analysis flagged the {('cardiovascular–respiratory axis' if hasCardiac else 'immune–hepatic interface' if hasFever else 'neuro–cardiovascular pathway')} as the highest-priority monitoring domain."
    
    recommendations = [
      "🫀 Initiate ECG monitoring and troponin assay immediately" if hasCardiac else "🩺 Schedule comprehensive metabolic panel within 48 hours",
      "🌡️ Administer antipyretics; blood cultures if temp > 39°C" if hasFever else "💊 Review current medications for interaction potential",
      "🫁 Supplemental O₂ therapy; consider chest X-ray" if spo2N < 94 else "🏃 Prescribe graduated aerobic exercise program post-stabilization",
      "📋 Schedule 14-day follow-up to re-run digital twin and compare trajectories"
    ]
    
    hr_arr = [hrN, hrN + 3, hrN - 5, hrN - 8, hrN - 10, hrN - 9, hrN - 8]
    sbp_arr = [sbpN, sbpN + 4, sbpN - 6, sbpN - 9, sbpN - 11, sbpN - 10, sbpN - 9]
    spo2_arr = [spo2N, spo2N - 1, spo2N + 1, spo2N + 1, spo2N + 2, spo2N + 2, min(99, spo2N + 2)]
    
    projectedTrends = {
      "labels": ["Day 0", "Day 15", "Day 30", "Day 45", "Day 60", "Day 75", "Day 90"],
      "heartRate": [max(55, v) for v in hr_arr],
      "systolicBP": [max(90, v) for v in sbp_arr],
      "spo2": spo2_arr
    }
    
    stats = [
      { "label": "CatBoost Severity", "value": f"{severity_score}/100", "color": "#ef4444" if risk == "Critical" else "#f97316" if risk == "High" else "#f59e0b" if risk == "Medium" else "#22c55e" },
      { "label": "Predicted LOS", "value": "4–6 days" if risk in ["High", "Critical"] else "2–3 days" if risk == "Medium" else "1–2 days", "color": "#f59e0b" },
      { "label": "Est. Wait Time", "value": wait_time, "color": "#06b6d4" },
      { "label": "Recovery ETA", "value": "~60 days" if hasCardiac else "~21 days" if hasFever else "~14 days", "color": "#10b981" }
    ]
    
    return FrontendSimulateResponse(
        overallRisk=risk,
        primaryCondition=primaryCondition,
        organSystems=organSystems,
        vitalStatus=vitalStatus,
        timeline=timeline,
        narrative=narrative,
        recommendations=recommendations,
        projectedTrends=projectedTrends,
        stats=stats
    )


