version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: digital_twin_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend/models/versions:/app/models/versions
      - ./backend/reports:/app/reports
